# This is the name of the workflow
name: Docker Build & Push

# When it runs
on:
  workflow_dispatch:
    # I can refer to these in the steps below
    # See https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
    inputs:
      moduleversion:
        description: 'Version of the module'
        required: true
        default: ''

defaults:
  run:
    shell: bash

# See https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: write-all

# And what jobs it has
jobs:
  # Just one job here ...
  build-linux-box:
    runs-on: ubuntu-latest
    # the steps of my job
    env:
    # Coz of https://github.com/orgs/community/discussions/45969 & https://github.com/docker/build-push-action/issues/755
      BUILDX_NO_DEFAULT_ATTESTATIONS: 1
    steps:
      # Checkout the code from GitHib
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup QEMU for building other platforms
      # # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          platforms: "linux/amd64,linux/arm64"
          # Only amd64 is supported for now in the Ubuntu image https://learn.microsoft.com/en-gb/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.4#ubuntu
          # thanks for the syntax https://github.com/docker/build-push-action/issues/557
          build-args: |
            GRAPH_VERSION=${{ github.event.inputs.moduleversion }}
          push: ${{ github.ref == 'refs/heads/main' }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description='PowerShell + MS Graph container'
          tags: |
            ghcr.io/rakheshster/docker-powershell-msgraph:${{ github.event.inputs.moduleversion }}
